apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: words-demo
resources:
  - ../base/
commonLabels:
  environment: staging    
replicas:
  - name: words-api-deploy
    count: 5
patchesStrategicMerge:
  - service_type_lb.yaml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: words-web-deploy
    path: web_env_patch.yaml
