apiVersion: apps/v1
kind: Deployment
metadata:
  name: words-api-deploy
  namespace: words-demo
  labels:
    app: words-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: words-api
  template:
    metadata:
      labels:
        app: words-api
    spec:
      containers:
      - name: api
        image: quay.io/garycncf/words-demo-api:version1
        env:
          - name: WORDS_DB_SERVICE
            value: words-db-svc
        ports:
        - containerPort: 8080
          name: api
