apiVersion: v1
kind: Service
metadata:
  name: words-api-svc
  namespace: words-demo
  labels:
    app: words-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: words-api
  selector:
    app: words-api
