apiVersion: apps/v1
kind: Deployment
metadata:
  name: words-db-deploy
  namespace: words-demo
  labels:
    app: words-db
spec:
  selector:
    matchLabels:
      app: words-db
  template:
    metadata:
      labels:
        app: words-db
    spec:
      containers:
      - name: db
        image: quay.io/garycncf/words-demo-db:version1
        ports:
        - containerPort: 5432
          name: db
