apiVersion: v1
kind: Service
metadata:
  name: words-db-svc
  namespace: words-demo
  labels:
    app: words-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: words-db
  selector:
    app: words-db
