apiVersion: apps/v1
kind: Deployment
metadata:
  name: words-web-deploy
  namespace: words-demo
  labels:
    app: words-web
spec:
  selector:
    matchLabels:
      app: words-web
  template:
    metadata:
      labels:
        app: words-web
    spec:
      containers:
      - name: words-web
        image: quay.io/garycncf/words-demo-web:version1
        env:
          - name: WORDS_API_SERVICE
            value: words-api-svc
        ports:
        - containerPort: 80
          name: words-web
